version: '3.9'

services:
    main:
        build:
            context: ./build/extend
            dockerfile: Dockerfile
        image: ${COMPOSE_PROJECT_NAME}/main
        container_name: ${CONTAINER_NAME_PREFIX}-Main
        hostname: ${CONTAINER_HOST_PREFIX}-main
        environment:
            - CHOKIDAR_USEPOLLING=true  # Enable Octane --watch working
        volumes:
            - ${VOLUME_MAIN}:${CONTAINER_WORKDIR_MAIN}
            - ./config/nginx/nginx.conf:/etc/nginx/sites-available/default
            - ./config/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./config/php/php.ini:/etc/php/${PHP_VERSION}/cli/conf.d/99-my.ini
        networks:
            default:
                ipv4_address: ${IPV4_MAIN}
        ports:
            - ${PORT_MAIN:-80}:80
            - ${PORT_MAIN_OCTANE:-8000}:8000  # Port assigned in supervisord.conf has higher priority
        working_dir: ${CONTAINER_WORKDIR_MAIN}
        command: >
            bash -c "cron start;
            supervisord -c /etc/supervisor/conf.d/supervisord.conf;
            nginx -g 'daemon off;'"
        restart: unless-stopped

    cache:
        image: ${DOCKER_IMAGE_VERSION_CACHE}
        container_name: ${CONTAINER_NAME_PREFIX}-Cache
        hostname: ${CONTAINER_HOST_PREFIX}-cache
        volumes:
            - ${VOLUME_CACHE}:/data
        networks:
            default:
                ipv4_address: ${IPV4_CACHE}
        ports:
            - ${PORT_CACHE:-6379}:6379
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']

networks:
    default:
        driver: bridge
        name: ${NETWORK_NAME}
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}
    share:
        name: ${SHARING_NETWORK_NAME}
